# Test your FastAPI endpoints

GET http://127.0.0.1:8001/
Accept: application/json

###

GET http://127.0.0.1:8001/brak/user/1315226075
Accept: application/json

###

GET http://127.0.0.1:8001/brak/kid/1315226075
Accept: application/json